# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9

pipelines:
  default:
    - step:
        name: Automated build and deploy
        deployment: staging   # set to test, staging or production
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -f searchEngineWebApp/pom.xml -B verify # -B batch mode makes Maven less verbose
  branches:
    master:
      - step:
          name: Automated build and deploy
          deployment: staging   # set to test, staging or production
          caches:
            - maven
          script:
            - mvn -f searchEngineWebApp/pom.xml -B verify # -B batch mode makes Maven less verbose
            - git subtree push -f --prefix searchEngineWebApp https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          

